apiVersion: v1
kind: Service
metadata:
  name: fuzi-bot-api
  namespace: fuzi
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30101
  selector:
     app: fuzi-bot-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fuzi-bot-api
  namespace: fuzi
spec:
  selector:
    matchLabels:
      app: fuzi-bot-api
  replicas: 1
  template:
    metadata:
      labels:
        app: fuzi-bot-api
    spec:
      containers:
      - name: fuzi-bot-api
        image: 192.168.2.101:5000/fuzi-bot-api:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: FUZI_SEARCH_URL
          value: http://192.168.2.101:30103
        - name: FUZI_NLU_URL
          value: http://192.168.2.101:30102